const fs = require('node:fs');
const assert = require('node:assert/strict');

assert.ok(fs.existsSync('index.html'), 'Expected root index.html for GitHub Pages');
const indexHtml = fs.readFileSync('index.html', 'utf8');
assert.ok(indexHtml.includes('<title>AgroCampo</title>'), 'Expected index.html to serve AgroCampo app');
assert.ok(indexHtml.includes('<div class="device-frame">'), 'Expected index.html to contain the app shell');

const html = indexHtml;

const mustContain = [
  'AGROCAMPO',
  'const state =',
  'actionSectorLocked',
  'window.addEventListener(\'hashchange\'',
  '#sector/',
  'data-route="#registrar"',
  '<div class="section"><h2>Labores</h2></div>',
  'data-labor="Riego"',
  'data-labor="Suelo"',
  'data-labor="Fertilizacion"',
  'data-labor="Control de Enfermedades y Plagas"',
  'Control de Enfermedades y Plagas',
  'selectedActivityType',
  'data-selected-type',
  "const laborButton=event.target.closest('[data-labor]')",
  '${type===state.selectedActivityType?\'selected\':\'\'}',
  'Cuadrante 3',
  'Conductividad',
  'Fertilidad',
  'Riego por goteo',
  'Riego por aspersion',
  'Riego por surco',
  'Riego por gravedad',
  'Calculo deterministico',
  'Pendiente de definicion funcional/agronomica',
  'function escapeHtml',
  'function syncPendingRecords',
  'function updateIrrigationEstimate',
  'function renderIcons',
  'function cropIcon',
  'const ICONS =',
  'const FRUIT_ICONS =',
  'raspberry.svg',
  "icon: 'raspberry'",
  'data-estimate',
  'data-crop-icon',
  'data-toggle-edit',
  'data-edit-panel',
  'sector-head',
  '.sector-head .edit-sector{order:3;margin-left:auto',
  'Editar cuadrante',
  'type="date"',
  'data-other-activity',
  'Seleccionar cultivo',
  'Cultivo seleccionado',
  'Parcela seleccionada',
  'Paso 2: Seleccionar accion',
  'Paso 3: Completar detalle',
  'data-action-detail',
  'Producto aplicado',
  'Duracion del riego',
  'Cantidad cosechada',
  "'#ia','sparkles','AgroIA'",
  '<strong>AgroIA</strong>',
  "['#registrar','#sensor','#riego'].includes(route)",
  '.send{width:50px;height:50px;border-radius:8px;border:0;background:var(--brand)',
  'data-vertex',
  'pointerdown',
  'setPointerCapture',
  'function updateDraggedVertex',
  'function transparentColor',
  'cropBg',
  'background:${cropBg(s.color)}',
  'ImagenSuperior.png',
  'mapSections',
  'background:${transparentColor(s.color,.34)}',
  'metric weather',
  '.metric.weather{background:#fff',
  'data-lucide="sun"',
  'data-route="#perfil"',
  'route===\'#inicio\'',
  'homeProfile',
  '--brand:#2A6E54',
  '--accent:#EDB240',
  '--bg:#FFFFFF',
  'border-radius:22px',
  '.btn.green{background:#fff',
  '.tab.fab i{width:28px;height:28px;background:#fff',
  '--display:"Inter",sans-serif',
  'Perfil',
  'Editar informacion',
  'Notificaciones',
  'Idioma',
  'Seguridad',
  'Tema',
  'Ayuda y soporte',
  'Contacto',
  'Privacidad',
  'Modo claro',
  'Mapa de Cuadrantes',
  'Resumen historial',
  'Abrir mapa',
  'Abrir historial',
  '<div class="section"><h2>Acciones</h2></div><div class="actions">',
  '#cambiar-cultivo',
  'function changeCropScreen',
  'data-change-crop-to',
  'data-route="#cambiar-cultivo"',
  'Seleccionar fruta',
  '<strong>Cambiar cultivo</strong>',
  '<strong>Ver historial</strong>',
  'event-card',
  '<div class="mark"><i data-lucide="${iconFor(item.type)}"></i></div>',
  '${cropIcon(s)}<span>${s.crop}</span>',
  'aria-label="Volver"',
  '.back{border:0;background:var(--brand);color:#fff',
];

const mustNotContain = [
  '#acciones',
  '<div class="section"><h2>Acciones rápidas</h2></div>',
  '<div class="section"><h2>Acciones rapidas</h2></div>',
  'function actionsScreen',
  'route===\'#acciones\'',
  'Recomendacion orientativa',
  'Verifica las condiciones reales del terreno antes de ejecutar una accion.',
  'Contexto activo',
  '<strong>IA</strong>',
  'Fraunces',
  'background:rgba(42,110,84,.24)!important',
  'data-save-vertices',
  'Ajustar seccion',
  'name="vertexX"',
  'name="vertexY"',
  '<div class="mark ${iconColor(item.type)}">',
  '<span class="tag">${escapeHtml(item.sync)}</span>',
  'Selector de parcela',
  'class="card ai-parcel-picker"',
  'data-ai-picker-toggle',
  'data-ai-picker-options',
  'data-ai-pick-sector',
  'aiPickerOpen',
  '--bg:#d8dde3',
  '--bg:#DCEFE7',
  '.quick .tile:nth-child(1){background',
  '<div class="btn-row"><button class="btn" data-route="#mapa"><i data-lucide="map"></i> Ver mapa</button><button class="btn ghost" data-route="#historial"><i data-lucide="history"></i> Historial</button></div>',
  "const nextCrop=s.crop==='Frambuesa'?'Arandano':'Frambuesa'",
  '.action:nth-child(1){background',
  'Prototipo High-Fi',
  'Prototipo Hi-Fi',
  'Decisiones de diseño',
  'screenTitle',
  'sideNote',
  'class="phone"',
  '<aside class="sidebar"',
  "${state.online?'Sincronizado':'Guardado local'}",
  'Parcela personal · trabajo en terreno',
  'Fertilidad demostrativa',
  'Media (demo)',
  'MEDICION DE SUELO',
  'Sensor fisico → usuario obtiene valores → AgroCampo',
  'Registro agricola',
  'Reemplaza el flujo cuaderno → Excel',
  'Comparacion entre temporadas',
  'Referencia demostrativa',
  'Mapa simulado',
  'ALERTA DE HELADA',
  'Riesgo elevado esta madrugada',
  'Sectores potencialmente afectados',
  'Interpretacion IA',
  'Comentario segun clima, historial y suelo',
  'Temporada Actual:',
  'Temporada Anterior:',
  'Acciones recientes',
];

for (const text of mustContain) {
  assert.ok(html.includes(text), `Expected HTML to contain: ${text}`);
}

for (const text of mustNotContain) {
  assert.ok(!html.includes(text), `Expected HTML not to contain: ${text}`);
}

const sectorMatches = html.match(/Cuadrante \d/g) || [];
assert.equal(new Set(sectorMatches).size, 3, 'Expected exactly 3 quadrants in the prototype');

assert.ok(!/\.q3\{left:\d+px/.test(html), 'Expected map quadrants not to rely on fixed 320px-breaking coordinates');
assert.ok(!/\.q6\{left:\d+px/.test(html), 'Expected map quadrants not to rely on fixed 320px-breaking coordinates');
assert.ok(/state\.syncQueue\.length=0/.test(html), 'Expected online sync simulation to clear pending queue');
assert.ok(/escapeHtml\(msg\.text\)/.test(html), 'Expected chat messages to be escaped before rendering');
assert.ok(/escapeHtml\(item\.notes\)/.test(html), 'Expected history notes to be escaped before rendering');
assert.ok(!/lucide\.createIcons\(\)/.test(html), 'Expected icon rendering to go through resilient renderIcons fallback');
assert.ok(!/simulad|prototipo|demo|demostrativ|Validacion/.test(html), 'Expected visible/product copy not to describe the UI as mockup or simulation');
assert.ok(/state\.mapSections\.map/.test(html), 'Expected map to render from mapSections instead of all sectors');
assert.ok(/mapSections:\s*\[[\s\S]*sectorId:\s*1[\s\S]*sectorId:\s*2[\s\S]*sectorId:\s*3/.test(html), 'Expected map to start with 3 editable sections');

console.log('AgroCampo acceptance checks passed');
