import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';

/// UI sound effects from master.md "Sonido". Each value maps to an OGG
/// asset generated by `tool/generate_sounds.sh`.
enum AgroSound {
  /// Short click for primary buttons.
  tap('sounds/tap.ogg', 0.5),

  /// Gentle confirmation for settings, profile and export saves.
  saved('sounds/saved.ogg', 0.7),

  /// Distinctive arpeggio for a saved agricultural record.
  recordSaved('sounds/record_saved.ogg', 0.8),

  /// Low descending pair for failed saves or invalid fields.
  error('sounds/error.ogg', 0.7);

  const AgroSound(this.asset, this.volume);

  final String asset;
  final double volume;
}

/// Plays [AgroSound]s. Implementations must never throw: sound is
/// complementary feedback and a failing speaker cannot break a save flow.
abstract interface class AgroSoundEffects {
  Future<void> play(AgroSound sound);

  Future<void> dispose();
}

/// No-op player used by default (tests, previews, platforms without the
/// audio plugin). Production binds [AudioplayersSoundEffects] at bootstrap.
final class SilentAgroSoundEffects implements AgroSoundEffects {
  const SilentAgroSoundEffects();

  @override
  Future<void> play(AgroSound sound) async {}

  @override
  Future<void> dispose() async {}
}

/// `audioplayers` implementation. Players are created lazily, one per sound,
/// in low-latency mode. The audio context uses the sonification usage and
/// requests no audio focus, so music or navigation from other apps keeps
/// playing and the system ringer/silent mode is respected.
final class AudioplayersSoundEffects implements AgroSoundEffects {
  AudioplayersSoundEffects();

  static final _context = AudioContext(
    android: const AudioContextAndroid(
      contentType: AndroidContentType.sonification,
      usageType: AndroidUsageType.assistanceSonification,
      audioFocus: AndroidAudioFocus.none,
    ),
    // Ambient already mixes with other audio and honours the silent switch.
    iOS: AudioContextIOS(category: AVAudioSessionCategory.ambient),
  );

  final Map<AgroSound, Future<AudioPlayer>> _players = {};

  @override
  Future<void> play(AgroSound sound) async {
    try {
      final player = await (_players[sound] ??= _create());
      await player.stop();
      await player.play(AssetSource(sound.asset), volume: sound.volume);
    } on Object catch (error) {
      debugPrint('AgroCampo sound "${sound.name}" skipped: $error');
    }
  }

  Future<AudioPlayer> _create() async {
    final player = AudioPlayer();
    await player.setAudioContext(_context);
    await player.setPlayerMode(PlayerMode.lowLatency);
    await player.setReleaseMode(ReleaseMode.stop);
    return player;
  }

  @override
  Future<void> dispose() async {
    final players = _players.values.toList();
    _players.clear();
    for (final player in players) {
      try {
        await (await player).dispose();
      } on Object catch (_) {}
    }
  }
}
